equinor/segyio

- .travis.yml
- CMakeLists.txt
- README.md
- cmake/find_python_module.cmake
- cmake/python.cmake
- cmake/python_module_version.cmake
- cmake/segyio_testing.cmake
- python/CMakeLists.txt
- tests/test_utils.c
- tests/unittest.h
Depends on pull request #16 
- Added support for building on MacOS on Travis
- Made it possible to disable Python wrappers
- Building of Debug initializes Valgrind test
- Checks if Numpy module is available
- Dynamically generates the PYTHON_INSTALL_PREFIX
> Build and test on macOS

- python/segyio/CMakeLists.txt
- python/segyio/_raw_trace.py
- python/segyio/_segyio.c
- python/segyio/_trace.py
- python/segyio/segy.py
- tests/test_segy.py
- tests/test_segyio_c.py
Trace.raw mode for eager reading of traces
Adds support for the raw trace sub mode that does eager reading of
traces into an MxN numpy array - a useful feature for segyview and other
visualisation tools when it is known beforehand that the file will fit
in memory.
> Trace.raw mode for eager reading of traces

- python/segyio/_segyio.c
- src/segyio/segy.c
- src/segyio/segy.h
- src/segyio/util.h
- tests/test_utils.c
Restrict aliasing slightly and remove a source of undefined behaviour by
casting float pointers to uint32_t. Reimplements the ieee<->ibm
functions to work on one float at the time without triggering undefined
behaviour.
> Remove undefined pointer casts

- tests/test_segy.c
Mostly to get rid of a super-annoying warning. We're not actually writing to the file anyway, so the dangers were non-existent and this file too should be inconsequential.
> Prefer random filename over tmpnam

- python/segyio/__init__.py
- python/segyio/_field.py
- python/segyio/_header.py
- python/segyio/_line.py
- python/segyio/_raw_trace.py
- python/segyio/_trace.py
- python/segyio/segy.py
Some simple __repr__ to help developers and researchers using segy interactively.
Demo:
```
Python 2.7.5 (default, Oct 11 2015, 17:47:16) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import segyio
>>> f = segyio.open("tests/test-data/small.sgy")
>>> f
SegyFile('tests/test-data/small.sgy', 'r', iline = 189, xline = 193)
>>> f.header
Header(traces = 50)
>>> f.bin
{JobID: 0, LineNumber: 0, ReelNumber: 0, Traces: 25, AuxTraces: 0, Interval:
4000, IntervalOriginal: 0, Samples: 50, SamplesOriginal: 0, Format: 1,
EnsembleFold: 0, SortingCode: 0, VerticalSum: 0, SweepFrequencyStart: 0,
SweepFrequencyEnd: 0, SweepLength: 0, SEGYRevision: 0, Sweep: 0, SweepChannel:
0, SweepTaperStart: 0, SweepTaperEnd: 0, Taper: 0, …
```
> __repr__ support

- mex/test/spec.m
- python/CMakeLists.txt
This file used to operate on the shared test-data/small.sgy, which made
tests break on the second run (which isn't picked up by CI).
> python.example.write gets private write.sgy file

- .travis.yml
Travis marks failures in before_script as errors and script as failed.
> Only make & test in script to mark failed/error

- cmake/check_includes.cmake
- lib/src/segy.c
- lib/src/segyio/util.h
- lib/test/segy.c
The use of size_t for file positions uses an implicit conversion to
long for calls to fseek and friends. Long is *not* guaranteed to be
64-bit, so this effectively restricts portable support for very large
files.
segy_seek has been rewritten to consider LONG_MAX and doing repeated
relative seeks should the position overflow a long. On most platform
this path should not be taken and optimised out.
> Handle 4G+ files on sizeof(long) == 4 platforms.

- lib/src/segy.c
- python/CMakeLists.txt
- python/segyio/_segyio.c
Previously this was enforced by the python C bindings, but this is
common functionality to ensure correctness on multiple platforms, so it
makes sense to have it in the shared C core.
> Ensure that files are always open in binary mode

- applications/segyinfo.c
- applications/segyinspect.c
- cmake/matlab.cmake
- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/src/segy.def
- lib/src/segyio/util.h
- lib/test/segy.c
- mex/segy_get_header_mex.c
- mex/segy_get_offsets_mex.c
- mex/segy_get_ps_line_mex.c
- mex/segy_put_headers_mex.c
- mex/segy_put_traces_mex.c
- mex/segy_read_write_line_mex.c
- mex/segy_read_write_ps_line_mex.c
- mex/segyspec_mex.c
- mex/segyutil.c
- mex/segyutil.h
- python/segyio/_segyio.c
- python/segyio/create.py
- python/segyio/open.py
- python/test/segyio_c.py
The mixture of signed and unsigned and various int types was largely an accident, and this PR attempts to clean up most of this. In short:
* All signatures have been reviewed and unless there's a good reason for some variable *not* to be int, it's int.
* The trace0 function still uses long, in order to be immediately associated with `fseek`. Overflow here isn't a problem since the trace0 is rather early in the file.
* Some explicit casts are added to silence conversion warnings that are deemed safe.
* `sample_indexes` have been renamed to `sample_indices` to be consistent with the rest of segyio, and has its argument shuffled around. Additionally, the arguments for this functions are now floats (as that's what we're working with in segyio) instead of doubles.
> Remove unsigned in interface

- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/src/segy.def
- lib/test/segy.c
- python/segyio/_segyio.c
Reading depth slice (or generaelised to any partial trace) can be done
with the segy_readsubtr function, which also now is the implementation
of segy_readtrace. Analogous for writing.
Rough measurements indicates that this speeds up depth_slice use by a
factor of 5.
> Read/write sub traces and speed up depth reading.

- lib/src/segy.c
File sizes often go over the range of what an int can represent, so the
intermediary type should be long long or some other >32bit type.
> Don't truncate filesize temporary.

- mex/segy_put_traces_mex.c
The old computation was straight-up wrong - now uses the same algorithm
as get_traces.
> Correct first/last index in mex/put_traces

- lib/include/segyio/segy.h
- lib/src/segy.c
- mex/segy_get_traces_mex.c
- mex/segy_put_traces_mex.c
- python/segyio/_segyio.c
When large amounts of traces are collected in one go, it usually means a
high number of samples too. This risks integer overflow, typically
happening for files >8G, which are common. segy_to/from_native taking
long long for size fixes this issue.
> Avoid overflow on large chunks in segy_to_native

- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/test/segy.c
- python/segyio/_segyio.c
Replaces the first-last interface of read/write_subtr with
start/stop/step, analoguous to python slices. With a step of 1, the most
common case, this covers the old chunk read, but the step allows greater
flexibility and maps nicely to features commonly found in higher-level
languages.
> Subtrace support for start/stop/step

- python/segyio/__init__.py
- python/segyio/_segyio.c
- python/segyio/tools.py
- python/test/tools.py
Exposes segy-to-native float conversion so that it can be used from
python.
> tools.native - convert from segy to native float

- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/src/segy.def
- lib/test/segy.c
- mex/Segy.m
- mex/segy_get_header_mex.c
- python/segyio/_segyio.c
- python/segyio/segy.py
- python/test/segy.py
A common use case is to inspect some property of a file by scanning
through all or a subset of headers and look at one field in particular.
Doing this operation in a scripting language over medium and large files
is very computationally expensive, but it's rather cheap if you drop
down in C.
The new function segy.attribute leverages the segy_field_forall function
to support reading some field across the full file or parts of the file.
Uses cases include learning things about a new file, make assumptions on
structure and plot ensembles, CDP etc.
The interface is designed to quickly give control to numpy or other
third-party libs, and the return value is always an array or a simple
value. Supports looking up attributes for a single trace, a range (via
slice operations [start:stop:step]) or …
> Read field forall

- lib/src/segy.c
- python/segyio/segy.py
segy_seek when the file is mmap'd is a pointer bump, and it's only
necessary to check for seek errors for the first/last trace. If both
these are fine then all traces between them are obviously fine, and we
don't need to check the error 
xrange is aliased to range for python2.
> Don't check seek errors in mmap-case loop

- python/segyio/_segyio.c
- python/segyio/open.py
- python/segyio/segy.py
- python/test/segy.py
- python/test/segyio_c.py
Support opening files without a reasonable geometry, or that are in some
other way unsorted. Opens up a use case where segyio is used to read
files not yet stacked, organised by lines, but still has useful
properties or interesting data.
The default behaviour is to assume a file is sorted, and raise an
exception if this cannot be figured out.
--
If anyone have any ideas on a better exception to throw than ValueError when accessing structured properties (iline, xline, depth) on an unstructured file, please voice it. I *think* it's the best one, but it feels a bit iffy still.
> Unstructured open

- lib/include/segyio/segy.h
- lib/src/segy.c
- mex/SegySpec.m
- python/examples/copy-sub-cube.py
- python/examples/make-file.py
- python/examples/make-ps-file.py
- python/segyio/_raw_trace.py
- python/segyio/_segyio.c
- python/segyio/_trace.py
- python/segyio/create.py
- python/segyio/open.py
- python/segyio/segy.py
- python/segyio/tools.py
- python/test/segy.py
- python/test/tools.py
Analoguous to file.xlines, file.ilines, file.samples is now a list of
samples and their identifiers. If possible, this is a list derived from
the binary- and trace headers with a recording delay t0 and a sample
interval. If these can't be figured out they're assumed to be 0 and
4000μs, 4ms, respectively.
As with the other identifiers, the cardinality is now obtained with
len().
The segy_sample_interval function would always assume that the interval
between sample describes distance-in-time (ms), but this is means a loss
of information when the data was in meters (which would be interpreted
as millimeters). Instead, this function now returns the inferred
interval without modifications, leaving it up to the caller to determine
what the interval describes, and typically has more information …
> file.samples is list; samples are not always time

- lib/src/segy.c
- python/test/segy.py
Fixes an off-by-one error that wasn't caught by tests because our test
files are mostly zero and the mis-aligned read happened to not affect
the result.
The issue stems from get_field being aware of the 'field' argument being
1-index'd, but the preceeding fread and its buffer were not. seek+read
is simply made aware of the 1-indexing.
Our test files headers are mostly zeros. The field-forall function would
read from byte 189, but should've started at byte 188, and the test data
happens to have all bits in the least-significant byte. When this is
copied to the local buffer, it would then be *written* with the same
mis-aligned offset, and since this didn't interact with any other bytes
(they're all set to zero anyway), the read did not pick up on it. This
is verifyable by reading the bytes …
> Fix off-by-one error in non-mmap field_forall

- python/segyio/create.py
- python/segyio/open.py
- python/segyio/tools.py
- python/test/tools.py
The heuristic that separates between time/depth is broken, since the
sample rate for depth is millimeters, not meters. In other words, it is
impossible to figure out just by inspecting the file if sample interval
means time or depth. The entire tool is removed in favour of correctly
storing the samples as floats.
> Remove scale_samples; store samples as float

- python/segyio/open.py
- python/test/segy.py
For some uses, ignoring geometry means fewer headers scanned, which can
be useful for large files without meaningful xline/iline organisation.
> Support ignoring geometry in python.open

- python/segyio/_raw_trace.py
- python/segyio/_segyio.c
- python/segyio/_trace.py
- python/test/segy.py
- python/test/segyio_c.py
Under some conditions, perfectly fine int-like types would raise a type
error when passed to getitem. Instead of checking for isinstance(int),
a slice or an int-like type is expected, and we internally handle the
conversion to an actual int.
> Make trace.__getitem__ accept more int-like types

- lib/src/segy.c
Turns out the line_indices function was an early version of the
field_forall function, so it might as well be an alias for it. It reads
less from every trace, so it should be faster in most cases.
> Implement line_indices with field_forall

- mex/SegySpec.m
- python/segyio/open.py
- python/segyio/tools.py
Correctly compute samples by interpreting t0 as milliseconds, not
microseconds.
> Interpret delay recording time/t0 as milliseconds

- python/segyio/_header.py
- python/segyio/_line.py
- python/segyio/_raw_trace.py
- python/segyio/_trace.py
Instead of reading directly from file into arrays or buffers that might
already be given to users, read into secondary arrays. This way, when a
read operation fails, user arrays will not be corrupted.
> Make generator read-ops exception safe

- mex/SegySpec.m
This was changed to be python compatible (i.e. return milliseconds), but
for compatibility reasons (confirmed by tests), microseconds are
returned for samples.
> Return samples in microseconds in matlab

- mex/SegySpec.m
- mex/segyspec_mex.c
interpret_segycube expects its t0 argument in milliseconds, but the
underlying C functionality uses microseconds (to have consistent units
with sample rate).
> Correctly adjust mex/t0 argument to milliseconds

- python/segyio/tools.py
- python/test/tools.py
Add tools.wrap (textwrap.wrap()) to format f.text with a user specific width on each line (default 80)
> Added text header formatting output in segyio.tools

- README.md
The present Build Status image now hyperlinks to
https://travis-ci.org/Statoil/SegyIO.
> Update hyperlink to TravisCI Build Status

- python/segyio/_trace.py
- python/test/segy.py
Relax shape requirements on trace assignment, so that ranges of traces
(or multi-dimensional arrays) can be written to file.
> Write range of traces; f.trace[:] = foo

- applications/segyinspect.c
- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/test/segy.c
- mex/segyutil.c
- python/segyio/_segyio.c
This breaks binary compatibility, so a recompilation of all downstream projects *linking* to the C lib is necessary.
Figuring out sorting no longer assumes that offset 37 is always the word offset, but supports any arbitrary position, with the same byte-boundary restrictions as always.
Language bindings are not updated to take this by parameter, but they're a less invasive change. I'd like to see this change merged before we reach some distributed 1.x version.
> Arbitrary offset header word

- python/CMakeLists.txt
- python/segyio/__init__.py
- python/segyio/su.py
- python/test/segy.py
The su namespace provides aliases to binary- and trace field names with
Seismic Unix naming where possible, simpler porting and developer
familiarity.
> Provide SU binary/trace header field names

- .travis.yml
Github releases from tags automatically create source tarballs, but
they are unbuildable by default, because they lack the pycmake
submodule. In order to make tarball-based distribution easier, the
segyio-$tag-all tarballs are uploaded on every release.
> Travis: Upload tarballs w/submodules to releases

- lib/src/segy.c
- lib/test/segy.c
The read/write subtr functions can take a buffer for when the function
is to be called repeatedly for speed purposes, but will allocate
otherwise. However, the functions always tried to free this buffer, even
if it wasn't allocated by the function.
Check if the buffer was actually allocated by the functions before
attempting to free.
Tests are updated to check for this.
> Dont free caller buffer in read/write_subtr

- applications/test/catb.py
- applications/test/cath.py
The tests assumed that the build folder was called `build` and that it was inside the source folder, but this is not necessarily the case.
Since ctest is normally executed from the build folder, `../` should be correct
(Honestly I don't know if this breaks anything else, the tests pass on my machine)
> Remove hard-coded folder name from tests

- cmake/check_includes.cmake
- lib/src/segy.c
- lib/test/segy.c
Change the ftell implementation to use the ftello posix function ftello,
enabling 64-bit files on all systems, in partiuclar when long is a
32-bit and regular ftell won't work.
The order of the fstat/ftell macros are changed, preferring
non-underscore prefix'd function when available.
> Implement segy_ftell with ftello

- README.md
Change `print x` to `print(x)` in the README.
> [minor] Make print statements in README Python3 compatible

- applications/segyio-cath.c
- lib/src/segy.c
- python/segyio/segyio.cpp
A series of small improvements that covers code paths that doesn't happen runtime, but that clang's static analyser was unable to prove wouldn't happen.
> Zero-initialise temporaries and memory related improvements

- python/segyio/open.py
The exception raised when the global binary header couldn't be parsed
was less than helpful. The new exception gives a suggestion on what's
wrong.
> Improve error message when bin-header is broken

- python/segyio/tools.py
- python/test/tools.py
Resampling some survey is not an uncommon operation, and a rather high
level one, but the steps needed to do it requires familiarity with the
SEG-Y specification, field names and behaviour. This is a natural
burden for segyio to lift.
The function itself is straight forward - write the new sample rate and
delay into the respective binary and trace header fields, and update the
samples property of the file handle.
Closes #194
> segyio.tools.resample

- README.md
- python/segyio/create.py
- python/segyio/segy.py
- python/segyio/segyio.cpp
- python/test/segy.py
- python/test/segyio_c.py
Fixes https://github.com/Statoil/segyio/issues/235
> Create tracecount arg not in header

- python/test/segy.py
Only write the final trace+header in the 16-bit overflow python test.
This still covers the overflow case, but doesn't use the disk as much.
Closes https://github.com/Statoil/segyio/issues/240
> Only write last trace in 16bit overflow test

- config.sh
Previously, the i686 libc was available in the pypa manylinux image. It
seems that the commit 4c1c549 changed this upstream, which means our
config.sh needs upgrading.
[1] https://github.com/pypa/manylinux/commit/4c1c5496d86d85875126ac807d15c42fc2289a77
> Add glibc.i686 to config.sh

- .travis.yml
Pip is usually able to resolve, download, and use the pytest runner
dependency, but fails a lot on OS X, seemingly because of distutils
challenges. By installing it explicitly with the approperiate pip this
problem goes away.
> Install pytest-runner on travis

- python/test/__init__.py
- python/test/segy.py
- python/test/segyio_c.py
The decorator never actually called the underlying function, so some tests haven't been executed for a while.
The first commits fixes tests broken by the decorator (no public breakage, just minor test type errors and the likes), the final commit makes the decorator useful.
> Call decorated function in @tmpdir

- python/docs/conf.py
The `segyio.__version__` string is only properly set if
1. it's built with make and/or setuptools
2. a version.py file exists (distributed with the tarballs)
Neither of these are the case for readthedocs.io and other standalone
sphinx doc builds. Since they mostly fetch with git anyway, it's a
convenient fallback for better document versioning than every revision
being `0.0.0`
> Fall back to git-describe for version in conf.py

- lib/include/segyio/segyio.hpp
segyio.hpp rely on functionality from these headers, but they where not
included.
> Include string, memory and algorithm headers

- config.sh
- cppcheck/suppressions.txt
- lib/test/mmap.cpp
- lib/test/segy.cpp
Move from the BDD-section to TEST_CASE_METHOD. The goal is to make the
actual test shorter and more to the point, at the cost of slightly more
convoluted dependency chain.
> Use fixture + test-case for set-format test

- lib/src/segy.c
- lib/test/segy.cpp
The in- and crossline fields were checked for validity, but offsets were
happily ignored. This didn't have a proper test case, and slipped
through.
> Check that offset field is valid in sorting

- applications/CMakeLists.txt
- applications/segyio-catr.c
- man/segyio-catr.1
While segycatr takes range arguments as 1-indexed, it would still
print the first trace if 0 was given as --range or --trace. Hence, situasions
where the first trace was printed twice could occur. Now, zero is no longer
accepted as a vaule for --range or --trace. This behavior is added to man-page
> Fix an issue where segyio-catr printed the same trace twice

- config.sh
- python/docs/conf.py
Instead of downloading a pre-built binary in a tarball, get cmake from
the pip infrastructure. This is a manylinux image, built in the same
image as the segyio binary package.
While code-wise this is a simple change, it's a step towards bumping the
minimum require cmake version from 2.8.12 to the 3.x series.
> Get cmake3.x from pip in manylinux image

- appveyor.yml
- external/catch2/CMakeLists.txt
- lib/CMakeLists.txt
- python/CMakeLists.txt
- setup.py
No longer build both shared- and static objects by default. Instead,
properly respect the BUILD_SHARED_LIBS option.
The main motivation for this is to make the segyio-config.cmake behave
properly, and not allow downstream users to choose what to link against.
A nice side effect is simpler make files with less non-standard
configuration, and a simpler flow.
> Build segyio target shared/static from config

- python/segyio/create.py
- python/segyio/open.py
- python/segyio/segy.py
- python/segyio/segyio.cpp
- python/test/segyio_c.py
Use two-phase init for python file handle
Split the python file handle initialisation routine into two phases -
one for the physical, on-disk open, and one for filling out meta-data.
In short, instead of the previous interface of:
```
fd = segyio.SegyFile(...)
```
it's now necessary to do:
```
fd = _segyio.segyiofd(...)
fd.segyopen()
fd = _segyio.segyiofd(...)
fd.segymake(...)
```
for opening and making files, respectively. This does not leak into user
code, and is taken care of inside open and create.
This properly splits the open/create routines into separate functions,
instead of interleaving them with conditionals. This is a readability
win, at the cost of some minor duplication.
> Two phase init python fd

- lib/CMakeLists.txt
- lib/src/segy.c
- lib/test/segy.cpp
- python/test/segy.py
In reference to issue #274, segy_sorting now check offsets as well as il and xl when determining sorting. Additional tests are added to check the sorting for wonky files. 
This PR also include a modification to a python test where an unstructed file is created and then opened. This file would previously be categorized as sorted, and thus the test would succeed in opening the file in strict mode. The test will now try to open the file with ignore_geometry=True.
> Files with fields (il, xl, offset) = (0,0,0) are set to unsorted

- lib/test/matchers.hpp
- lib/test/segy.cpp
Move the custom matchers to a matchers.hpp to enable re-use across test
units.
> Move custom matchers to includable file

- lib/src/segy.c
- lib/test/segy.cpp
- python/segyio/segy.py
The wrong function (!) was called here, meaning memeory mapped writes
never really worked as expected. This was not caught by a test, because
the tests for this function use new files, and memory freshly-created
files has never been supported.
The write-sub-trace tests have been amended to also work with
memory-mapping. The new strategy for these tests to make a test-specific
copy of the small.sgy file, and open it in read-write mode, instead of
creating a new truncated test-specific file as before.
> Call write, not read, in mmap write-trace

- python/docs/segyio.rst
- python/segyio/depth.py
- python/segyio/segy.py
- python/test/segy.py
Closes #306 
See #305 
The directions for the slices got mixed up in 64476e7, which made the
shape of depth_slices wrong. The underlying read function goes in
increasing-trace order, or 'fast' direction, anything other than
fast-by-slow will be wrong.
There has been code supporting depth_slicing (fixed z-coordinate) across
the file for a long time, but it was protected with a ValueError
exception in the case of unstructured files. This restriction can be
lifted, as fixed z-coordinate access is perfectly reasonable even
without a proper volume.
> Depth slice shape fast by slow

- .travis.yml
- CMakeLists.txt
- cppcheck/suppressions.txt
- lib/CMakeLists.txt
- lib/experimental/segyio/segyio.hpp
- lib/test/segyio-cpp.cpp
segyio needs a more ergonomic and simpler interface for use in
high-performance C++ applications. For now, this feature is experimental
and will only be installed on systems when the -DEXPERIMENTAL=ON flag is
passed to cmake, and is not guaranteed to be stable between even two
commits.
The interface is designed to be highly efficient for *use* - most
programs don't really care about SEG-Y details at all, they just want to
read some seismic. Some applications care deeply about some details
(such as the presence of fast volume/cube access ). segyio-C++ was
designed to support both these cases, and to be able to statically
describe required and useful features of file handles.
The implementation should be suited for experimentation, but lacks both
maintainer documentation, user …
> Initial experimental C++ interface

- python/test/__init__.py
- python/test/segy.py
These fixtures provide a fixed baseline for creation of temporary
small.sgy and small-ps.sgy which is used for several test-functions
> Create tmpfiles with pytest.fixtures

- .travis.yml
- lib/CMakeLists.txt
- lib/test/mmap.cpp
- lib/test/segy.cpp
- lib/test/test-config.hpp
- lib/test/testsuite.cpp
Replace the include src.cpp way of parameterising tests with multiple
processes, a global config object, and command line options.
Every include would essentially add a constant compile time increase,
which is over time unsustainable (I measured compilation time to approx
3.5s per file on my laptop, which is excessive for 1500 lines).
Additionally, it made code ugly because every test tag has to be unique,
which was solved by defining a tag and prepending it to every test. This
does not compose too nicely, and would get increasingly worse.
There *will* be more cases of tests essentially being identical, except
some slight configuration change on the file handle. It's desirable to
run also these configurations through the full test suite.
Running the multiple configurations is now handled …
> Parameterise tests as separate processes, not tags

- lib/experimental/segyio/segyio.hpp
The implementations are in headers and will be included everywhere,
which could lead to linking problems unless marked inline.
> Make segyio::literals inline

- python/segyio/create.py
- python/segyio/open.py
- python/segyio/segy.py
- python/segyio/segyio.cpp
- python/segyio/tools.py
- python/test/segy.py
- python/test/segyio_c.py
Extend little-endian support to Python. The interface change is the
added option 'endian' in segyio.open, and the field endian in spec. By
default, segyio still behaves as always, and assumes big-endian.
For users, reading LSB files require explicit, external knowledge
> LSB support from Python

- python/segyio/open.py
- python/segyio/segy.py
- python/test/segy.py
Given a set off structure-defining parameters interpret() will
(re)interpret the structure of the file. This does not change the
file itself, it only changes segyio's interpretation of it.
Connects to #294
> Method for (re)interpret structure on an open file

- external/catch2/catch/catch.hpp
This false positive came with the release of clang-7 and is documented
both upstream at Catch and upstream at LLVM. For now, just suppress it,
as it breaks travis builds and provides no extra information.
> Suppress false positive null-deref in catch

- python/segyio/create.py
- python/segyio/segy.py
interpret() assigns ilines, xlines, and offsets labels by copy rather
then by reference. This should have been the case for the original
implementation of interpret()
Connects to #294 
Closes #294
> Use f.interpret() in segyio.create()

- python/docs/segyio.rst
- python/segyio/su/words.py
Sphinx isn't to helpful documenting undocumented module variables, so
help it on the way by adding empty special comments for every entry.
> Ensure su-words are picked up by sphinx

- python/segyio/trace.py
- python/test/segy.py
Update from discussion: my bad, didn't notice that if slice is provided, list (not one string) is expected as val . Updated the code to take first element from each provided Text.
> Fix Text.__setitem__ for Text parameter

- python/segyio/gather.py
- python/test/segy.py
When operating on slices, if offset slice is out of range, empty array
should be returned.
Fixed typo, added test.
> Fix typo in gather

- python/segyio/line.py
HeaderLine called Header with the wrong range, resulting in way to many
write operations when writing lines along the sorting  direction. I. e.
the same headers was written muliple times, tanking the performance.
Correcting the range reduced the function call complexity from  n^2
to n.
Example: Writing headers in iline mode on a iline sorted file:
1:        f.header.iline[n] = _
HeaderLine then called Header with:
2:       self.header[n0, :, stride] = _
where n0 is the first trace of iline n. In this case stride = 1, hence
we are writing all header from iline n to the end of the file. All
headers after line n is wronly assigned. However, in cases where the
entire file is updated with (1), the last assignment to each header
would still be correct, thus test has not picked up on this issue. …
> Write each trace only on time in HeaderLine

- python/segyio/create.py
- python/test/segy.py
If no explicit value for file specification is provided, segyio should
assume inline sorting is expected. Changed, updated one of the 'create'
tests
Fixes #292
> Change default segy.spec.sorting to inline

- changelog.md
- lib/src/segy.c
The HOST_MSB and HOST_LSB preprocessor variables are always set, meaning
that HOST_LSB will always be defined. The correct check is if, not
ifdef, and so code would always be little-endian
> Test endianness in segy.c properly

- README.md
- python/examples/make-file.py
- python/examples/make-ps-file.py
- python/segyio/tools.py
Writing headers line-by-line is a huge performance hit compared to
writing trace-by-trace
As it is not nessesarily obivious to the regular user that there is a
performance hit by writing line-by-line, the examples on how to create a
file should use trace-by-trace writing to encurage trace-by-trace
writing
connects #346 
closes #346
> Refactor from_array to write files trace-by-trace

- python/segyio/depth.py
- python/segyio/trace.py
- python/test/segy.py
Do the unpacking slice.indices when it is suspected the argument is a
range outside of the generator definition, and redirect the
AttributeError to a TypeError (which it really is). Otherwise the error
would first show up when the generator is accessed, instead of at the
actual site of error.
> Raise TypeError on f.trace[None]

- python/segyio/segyio.cpp
- python/test/segy.py
The segyio core expects that segy_set_format is called whenever files
do not use 4-byte numerics, but some other numeric size (such as 2-byte
ints and 8-byte floats).
This function was called in open, but never create.
> Call segy_set_format in py/segycreate

- lib/test/segy.cpp
Address sanitizers picks up on the buffer overrun. Without calling
segy_set_format, the read function _will_ read 4 bytes, not 2.
The test is improved slightly too by explicitly zeroing the memory and
verifying that something is indeed erroneously written to the second
element in the array.
> Make enough stack-space test missing set_format

- python/segyio/gather.py
- python/test/segy.py
The key misses here are legitimate, as lines don't have to start at
zero, and can have gaps. Key misses here are not errors, because the
range can be described as "anything in between an interval", without the
requirement that ranges are contiguous.
> Don't crash on key misses in f.gather[int, :]

- lib/src/segy.c
- python/test/segy.py
bswap32 cannot be indiscriminatly applied to the int32 temporary, as it
essentially is a byte-reorder and left-shift when applies to an int16.
The symptom is that certain header fields extracted this way show up in
the absurd range (some 65 million), when normal values are in the few
thousands, such as dt/sample-interval.
Addresses #368
https://github.com/equinor/segyio/issues/368
> bswap16 short header words in field_forall

- python/segyio/open.py
The docstring for open.py includes an example of copying
a file from a source to a destination.
In the previous version, this example uses the same filename
for the 'from' as for the 'to' open statements.
This could be confusing to users because, in practice,
a non-trivial use of this would need different filenames for the
'from' and 'to' open statements.
This commit gives two different filenames for 'from' and 'to'.
> Modify docstring for open.py to clarify copy operation

- README.md
Added hyphen to README.md:
'dict like' --> 'dict-like'
dict-like is used elsewhere in the readme,
and is the preferred way of writing this phrase.
This update adds a hyphen to one instance where
it had been left out.
> Fix grammar inconsistency in README.md

- lib/experimental/segyio/segyio.hpp
Check that (inlinecount * crosslinecount) == tracecount when
interpreting a file as volume.
> Check volume consistency when loading as volume

- python/segyio/tools.py
I strongly suggest  making the example either
```python
with segyio.open('post-stack.sgy') as f:
x = segyio.tools.collect(f.trace[:])
x = x.reshape((len(f.ilines), len(f.xlines), f.samples))
numpy.all(x == segyio.tools.cube(f))
```
or
```python
f = segyio.open('post-stack.sgy')
x = segyio.tools.collect(f.trace[:])
x = x.reshape((len(f.ilines), len(f.xlines), f.samples))
numpy.all(x == segyio.tools.cube(f))
f.close()
```
to make the examples beginner-friendly.
> Make Collect Example self-contained

- lib/experimental/segyio/segyio.hpp
- python/segyio/line.py
- python/test/segy.py
Assigning to headers for slices of lines or offsets were broken,
courtesy of the iterability check being inside the wrong block.
Move the block to the right scope, and add tests for the syntax.
> Fix header assignment in pre-stack files

- python/test/segy.py
A list being converted to a numpy array was causing a performance
warning to be emitted.
> Remove conversion warning

- python/segyio/depth.py
- python/segyio/field.py
- python/segyio/line.py
- python/segyio/trace.py
In python 3.8 [1], importing the abstract base classes from collections
will break. Simply changing the import is both backwards and forward
compatible.
[1] DeprecationWarning: Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated, and in 3.8 it will
stop working
Closes #403
> Import abstract base classes from collections.abc

- README.md
- python/segyio/create.py
The issue of slow header writes pop up quite often, and it's likely that
the culprit is actually a slow file system for sparse writes. It is
certainly useful to point this out in the common issues section in the
readme, as well as briefly mention sparse writes in the docs for create.
> Point out sparse file writes in common issues

- applications/segyio-catr.c
The control flow for the t/r-case is pretty heavy, and uses a goto for
early exit. This label was made a case label in the switch by accident,
which was happily jumped to, but is wrong and awkward.
Wrapping the whole case in a compound statement provides some micro
isolation, but more importantly makes the done label a proper goto
label, not a switch case.
Closes #436
> Wrap catr t/r arg parsing in compound statement

- python/CMakeLists.txt
The CMAKE_INSTALL_PREFIX is the canonical way to configure the prefix
path (defaults to /usr/local). The cmake system invokes the setup.py
install command, but needs the prefix if it is set - otherwise, use
whatever is default and don't pass the flag at all.
> Respect CMAKE_INSTALL_PREFIX in python-pkg install

- python/segyio/tools.py
- python/test/tools.py
The str(text) on the input in wrap was quite broken in python3, as
str(text) actually prepends the bytearray(b'') like in repr.
> Decode text in tools.wrap

- lib/test/segy.cpp
The helper function will always return or invoke the FAIL() macro, but
gcc under certain conditions complain:
segyio/lib/test/segy.cpp:534:1: warning: control reaches end of
non-void function [-Wreturn-type]
If the macro for some reason is not expanded correctly and this does not
abort, negative values should never pass a test for size and at least
mark the error. When FAIL() does abort (it should), the final return is
never reached.
> Avoid end of non-void warning in test.read-size

- python/CMakeLists.txt
This reverts commit 79f0863c5814a4a375ece345c1751cb6c99634f7.
This is not well enough tested before merging. CI quickly shows that
often, when using a cmake based install, a package is to be built, or
the prefix is somewhere not yet in PYTHONPATH. Setuptools opts to fail
the build in this case, and these flags turns off that behaviour. When
cmake is used to install the python package, it is to be expected that
reasonable care is taken that the prefix passed is the correct one, also
for python, and it does not make sense for setuptools to disagree with
that.
> Revert "Install package without --record/--single"

- python/CMakeLists.txt
Running cmake && make DESTDIR=/some/root with make as the generator puts
the build-tree shared object puts the _skbuild dir at DESTDIR, as the
scikit-build make install invocation respects DESTDIR. DESTDIR and
python is already handled by our cmake scripts, so simply hide the fact
that it is in use by deleting it from the env when calling python.
> Hide DESTDIR from scikit-build

- python/setup.py
The scikit-build internal install step must specifically not respect
DESTDIR, as it is a part of the python library build phase, not install
phase.
> Remove DESTDIR from MAKEFLAGS env var in setup.py

- .travis.yml
- requirements-doc.txt
- requirements-readthedocs.txt
The gallery uses matplotlib internally, but there is no direct
dependency on it. Add a new requrements-doc.txt for doc-specific
requirements for easier management.
> Add requirements-doc.txt, matplotlib for gallery

- python/segyio/trace.py
- python/test/segy.py
The intention was always for f.trace[i,j] to return a single sample when
i and j were both integers:
assert f.trace[0, 1] == f.trace[0][1]
However, this evaluated to true when [i, j] returns an array, since the
result of the comparison is array([True]), and which is not falsy.
Reported in https://github.com/equinor/segyio/issues/475
> Return single sample in f.trace[i,j] for ints

- applications/flip-endianness.cpp
- cppcheck/suppressions.txt
cppcheck v2.1 produces some false positives that would be akward or just
a lot of noise to fix. Suppress them for now, and hope that cppcheck
either fixes these cases, or rewrite the code into a style cppcheck
prefer at some later time.
> Suppress cppcheck false positives

- .travis.yml
The brew update often fails and using addons is more elegant than
manually invoking brew behind platform guards. This makes the config
simpler, and should prevent some macos job failures [1].
[1] such as https://travis-ci.org/github/equinor/segyio/jobs/731298536
> Run homebrew through addons on travis

- python/segyio/segyio.cpp
The with-length argument type specifier would be either int or
Py_ssize_t, depending on the PY_SSIZE_T_CLEAN macro being defined.
From the docs:
For all # variants of formats (s#, y#, etc.), the type of the length
argument (int or Py_ssize_t) is controlled by defining the macro
PY_SSIZE_T_CLEAN before including Python.h. If the macro was defined,
length is a Py_ssize_t rather than an int. This behavior will change
in a future Python version to only support Py_ssize_t and drop int
support.  It is best to always define PY_SSIZE_T_CLEAN.
https://docs.python.org/3/c-api/arg.html#arg-parsing
In python3.8, using ints for lengths (i.e. not defining
PY_SSIZE_T_CLEAN) is considered deprecated, and in future versions of
python only Py_ssize_t will be legal.
From the docs:
It is recommended to …
> Use Py_ssize_t for type-length arguments

- python/pyproject.toml
- python/setup.cfg
Possibly creating issues for komodo, and is pep518 compliant.
> Prefer build-system.requires over setup_requires

- python/segyio/line.py
Starting from Python 3.12 slice is hashable. Passing a slice as a dict key will thus no longer yield a TypeError. We were checking for this as a means to trigger an alternative codepath in the case where the key was a slice.
> Use isintance to check if key is a slice

- .github/workflows/build.yaml
- .github/workflows/wheels.yaml
The macOS-10.15 runners are no longer available. Update to macos-latest runners.
> Build for macOS on macos-latest runner

- changelog.md
- python/setup.cfg
PyPI recets the latest build because the metadata was not updated for the new release.
```text
[...]
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking artifact/segyio-1.9.11-cp39-cp39-win32.whl: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking artifact/segyio-1.9.11-cp39-cp39-win_amd64.whl: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Uploading distributions to https://upload.pypi.org/legacy/
Uploading segyio-1.9.11-cp310-cp310-macosx_10_9_x86_64.whl
25l
0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/90.1 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB • 00:00 • 3.9 MB/s
100% …
```
> Bump version tag to 1.9.12

- .github/workflows/build.yaml
- .github/workflows/wheels.yaml
- python/segyio/open.py
- python/setup.py
- python/test/segyio_c.py
This line was causing a  error due to an update to scikit-build.  The issue was that the setuptools.command.test module is not put into the symbol table by the setuptools import, but it was put there during the skbuild import causing it to be available. Due to changes in scikit-build this is no longer the case and the line gives an AttributError.
The rationale for this line was that scikit-builds test command implied develop (this was obnoxious), something that is no longer true. There is thus no longer any reason to keep this line, so we can fix this issue by simply removing it.
> Fix attribute error in setup.py

- python/docs/conf.py
- requirements-readthedocs.txt
Looks like after fixing readthedocs builds we need to specify the theme explicitly.
Also sphinx got updated. In new version content tree doesn't look the same anymore and is cluttered with domain objects. This new feature needs to be turned off to look the same as before.
Currently:
Before:
With this PR:
> Bring back old readthedocs look

- applications/segyio-catb.c
- applications/segyio-cath.c
- applications/segyio-catr.c
- applications/segyio-crop.c
During compiling the functions without parameter definition gives warnings.
> Fix declaration without a prototype warning

- .github/actions/benchmark/action.yaml
- .github/workflows/benchmarks.yaml
Current logic is flawed.
Intention of benchmark tests was to build library from two different commits. However only C/C++ part was built separately, python code was not touched.
When current commit's directory was checked out to run the fresh tests, so was other python code: tests were always run on the same python part of the library.
To fix that, build a local wheel from existing code and make sure it is being used instead of local code.
> Fix benchmark CI

- CMakeLists.txt
- README.md
- external/catch2/CMakeLists.txt
- lib/CMakeLists.txt
- python/CMakeLists.txt
- python/setup-CMakeLists.txt
Red Hat Enterprise Linux (RHEL) 7 has reached its end of life in 2024. This means we can bump the minimum required version to 3.11 which is provided in RHEL 8 [1]. We assume that other systems either have CMake 3.11 or newer available, or have a way to install a sufficently new CMake versions.
Bumping the minimum version removes some deprecation warning (about support for older CMake versions being dropped), and also ensures compatibility with CMake 4.0 which has dropped support for CMake <3.5 and was rolled out to GitHub runners recently.
[1]: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#platform-tools
> Bump minimum CMake version to 3.11

- .github/workflows/benchmarks.yaml
- python/examples/make-file.py
- python/examples/make-ps-file.py
- python/segyio/create.py
- python/segyio/tools.py
- python/test/tools.py
- Today's benchmark test fixes
- Fixes to the binary header values
Note: I suspect that file creation through `tools.from_array` might fail for users as set trace fields are 2 bytes (trace number, sample count). We just don't have big enough tests to confirm this. Probably would be best to create them one we have extended trace headers in place.
> Fix of recently failing CI

- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/test/segy.cpp
- python/test/segy.py
Reading and writing values to the trace header and binary file header only used the datatype size and not the type. In this PR the tables are updated to store data type. The datatype will enable the access of float fields in the future. 
Currently the "Benchmark" test is writing int values that are greater than 2^16 to int16 fields. This raises an exception and causes the Benchmark test to fail. It should be possible to review this PR and then postponed the merge step until this issue is resolved.
> Reading and writing fields using field datatype 

- .github/workflows/analyzers.yaml
- lib/experimental/segyio/segyio.hpp
- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/test/segy.cpp
The objective is to run cppcheck during rebase testing. Adding suppress comments such that the codebase can pass without error or warning flags being raised.
> Suppress cppcheck exceptions

- applications/apputils.c
- applications/apputils.h
- applications/segyio-crop.c
In preparation for reading fields with data type float I want to simplify the code. 
Functions bfield and trfield returns -1 in case of error. For most fields -1 is a valid value. Not all cases using these functions check for -1. Remove the functions and ignore the error code in cases it is not checked.
> Remove bfield and trfield

- .github/actions/benchmark/action.yaml
- python/test/benchmarks.py
- python/test/segy.py
Shall see how this set of tests behaves in future.
- Might reduce number of files, if two files doing the same work just spoils the picture.
- Shall see if file size is good enough. I am not yet sure if relative performance depends on file size or not.
- Together with c-datasource PR `update_by_depth` test was very unstable and `sparse_samples` was certainly slower, but as I slightly updated the criteria (size and how much information is retrieved) , will see how it goes now. Might as well be some weird VM-slowness :woman_shrugging:
> Update benchmark test suite

- python/segyio/create.py
- python/segyio/depth.py
- python/segyio/field.py
- python/segyio/line.py
- python/segyio/open.py
- python/segyio/segy.py
- python/segyio/segyio.cpp
- python/segyio/su/file.py
- python/segyio/tools.py
- python/segyio/trace.py
- python/test/segyio_c.py
At the moment we have a lot of entities with name "fd" in it, which likely stands for "file descriptor". As we no longer operate on files, but on an abstract datasource, it is better we rename the classes and variables that have some reference to that.
Alex and I agreed that we want to do some name changes due to having broader io support, but we did not agree on the scope.
I believe proposed changes improve situation, but if reviewer has something against new names, will gladly hear it :cat:
> Rename entities to reflect broader io support

- lib/include/segyio/segy.h
- lib/src/segy.c
- python/segyio/create.py
- python/segyio/open.py
- python/segyio/segyio.cpp
- python/segyio/su/file.py
- python/test/segyio_c.py
Python end-user code is planned to be added in the next PR. 
segyio tests will be added in it as I/O methods are not supposed to be called directly from Python, but via other segyio functions. So it must be tested as a whole.
Lack of running examples might make this PR difficult to review though, so commits introducing datasource for users can be added if desirable.
> Expose datasources to python bindings

- .github/workflows/wheels.yaml
- applications/segyinfo.c
- applications/segyio-catb.c
- applications/segyio-cath.c
- applications/segyio-crop.c
- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/src/segy.def
- lib/test/segy.cpp
- mex/segy_get_traces_mex.c
- python/segyio/segyio.cpp
C get/set field cleanup that came up before and during proof-of-concept implementation for tracemaps.
Seems like nothing of the removed code is needed as it still would be us who would parse and return all fields from all trace headers.
> Segy field data cleanup

- .github/workflows/analyzers.yaml
- lib/include/segyio/segy.h
- lib/src/segy.c
- lib/src/segy.def
- lib/test/segy.cpp
- python/segyio/create.py
- python/segyio/open.py
- python/segyio/segy.py
- python/segyio/segyio.cpp
- python/segyio/tools.py
- python/segyio/trace.py
- python/segyio/utils.py
- python/test/segy.py
- python/test/segyio_c.py
- python/test/tools.py
1. ASCII encoding support was added as it was requested several times already.
2. EBCDIC tables are updated according to SEG-Y specification.
3. Not yet done string-related breaking changes are applied, as well as I understood them.
Those might cause some slight breaking changes for the users, but most likely only if files were weird-ish or there was some hardcoded way to deal with ASCII files.
Note: even though strings and encodings are now supported, Trace Header bytes 233-240 are not updated to read string from it. I did that originally, but then after discussion with PO we agreed to leave Unassigned 1 and Unassigned 2 as is. Reason for this is that in revision 1.0 space is defined as
`233-240 Unassigned — For optional information`
and someone might have used that as ints before.
> Improve strings handling

- python/segyio/tools.py
The `collect` example was depicting to reshape based on `f.samples` - an array, instead of `len(f.samples)`
> docs: adjusted `collect` example
