equinor/segyio

examples/CMakeLists.txt, examples/segyviewer.py, python/segyio/segy.py, tests/test_segy.py
And added depth_plane functionality in python layer
=> Added GUI segyviewer as an example

examples/CMakeLists.txt, examples/scan_min_max.py
=> Scan for min max sample

examples/segyviewer.py
Fixing some duplicate imports and removing some old comments
=> Cleaning up imports and comments

CMakeLists.txt, tests/CMakeLists.txt
If missing licenses for mcc, or problem with license server
=> Optionally turn off building of matlab tests

python/CMakeLists.txt
...  if Python interpreter or Numpy version fails.
=> Ensure that Python tests are not run

MANIFEST.in, setup.py
It is now possible to write:
`pip install segyio`
=> Added Python packaging

src/segyio/segy.c, tests/test_segy.c
uint16_t -> int16_t -> int32_t
=> Correct cast for reading short header field

cmake/python_module_version.cmake, python/CMakeLists.txt
update pycmake to latest version from https://github.com/Statoil/pycmake
=> update pycmake and require numpy 1.6

python/segyio/segy.py
Depth slices had crossline and inline directions mixed up.
=> Fixed depth slice shape

python/segyio/_header.py, python/segyio/_line.py, python/segyio/_trace.py, python/segyio/segy.py
More Python 3.X changes to the python code
=> Trying to move the python code to be py3k compatible

python/segyio/_line.py, python/segyio/_segyio.c, python/segyio/create.py, python/segyio/open.py, python/segyio/segy.py, src/segyio/segy.c, src/segyio/segy.h, tests/test_segy.c, tests/test_segyio_c.py
Adds functionality for figuring out the offset numbers and stores them in the python object, not just the cardinality.
Depends on https://github.com/Statoil/SegyIO/pull/53
=> Store offset indices

examples/showcase_gui.py, python/segyview/CMakeLists.txt, python/segyview/__init__.py, python/segyview/layoutcanvas.py, python/segyview/layoutfigure.py
Added a LayoutCanvas for managing sub plots in `matplotlib` depends on PR #59 and PR #60
=> Layout Canvas Widget

python/segyio/_segyio.c, python/segyio/segy.py
Moved implementation of dept slice reading from Python to C
Non-scientific performance increase: ~39x
=> Faster depth slice reading

changelog.md
=> Changelog for November 2016

python/segyio/__init__.py, python/segyio/segy.py, python/segyio/tools.py, python/test/tools.py
Collect handles the common case of copying a series of traces, lines,
slices into one stacked numpy array.
Cube attempts to read a full cube from a file or file handle and returns
the data as a 3D numpy array.
=> tools.collect and tools.cube

lib/src/segy.c
Changes significant aspects of float conversions (segy_to/from_native):
* The algorithm itself has been simplified. I suspect this leads to
better optimisation opportunities, because it's a lot faster all other
things being equal.
* Conversion is now done in-place always, instead of a hybrid to/from
range-oriented interface.
* The actual conversion is moved into new static inline functions,
which seem to guide the compiler to create better (maybe even
vectorised) code when converting large arrays of floats.
* host <-> network byte order is done *before* any float conversion,
meaning there are fewer instruction dependencies at the cost of
traversing the array twice. This also makes each loop step simpler and
it seems to optimise slightly better.
=> Faster float conversions

lib/include/segyio/segy.h, lib/src/segy.c, python/segyio/_segyio.c
A couple of small fixes (gcc reports them as warnings).
=> Signed segy binheader size

python/segyio/_segyio.c
Under some error conditions certain buffers would not be properly
free'd.
=> Plug buffer leaks.

README.md
https://github.com/Statoil/SegyIO/issues/106
=> Update readme build instructions and spelling

python/CMakeLists.txt, python/segyio/_gather.py, python/segyio/segy.py, python/test/segy.py
Support for reading data from some intersection in a cube.
=> Gather mode

python/segyio/segy.py
Initial commit to get things going and see that workflow works fine.
=> Relocate instance creation to constructor - reduce runtime

README.md
Link to the netcdf_segy tool by Alan Richardson in the readme, with link
to the project and the notebook demo.
=> Link to netcdf_segy in README.

python/segyio/_gather.py
Doing ranges over gather was very slow, because it's essentially a
trace-by-trace read with the additional cost of a line-number
intersection -> trace index translation. This work was done in pure
python and once-per-trace with pretty terrible performance.
The immediate use case for gather mode is obviously looking up just a
handful of traces, but the examples and obvious code also considers
ranges, which translate to sub cubes.
In order to improve the performance of the range-over-gathers feature, a
simple way is to simply read more traces as once an buffer them, and
avoid doing too many and too expensive index translations.
Since range-over-gather essentially boils down to reading along an
inline, using the inline mode to do the physical reading, this can be
used to buffer traces. …
=> Buffer gather-ranges by reading lines

README.md
=> Add readme-badges for appveyor and pyup

python/examples/about.py, python/examples/write.py, python/segyio/_field.py, python/segyio/_trace.py, python/segyio/create.py, python/segyio/segy.py, python/segyio/tools.py, python/test/test_context.py
Fixes a small error in docstring and updates string formatting
=> String formatting

python/segyio/segyio.cpp
The exception messages when segyio.tools.dt fails were less than
helpful, and essentially a direct dump of errno after a failed fread
call, which isn't very helpful, especially when a file is corrupted.
Clarify the exception by making it runtime error (since the file was
already open) and saying whether it was binary- or trace header reading
that failed.
Considering the tiny test program:
```
segyio.tools.metadata(filename)
with segyio.create("foo.sgy", spec) as g, segyio.open(small.sgy) as f:
zeros = np.zeros([len(f.trace), len(f.trace[0])], dtype = np.single)
segyio.trace = zeros
segyio.tools.metadata("foo.sgy")
```
Without this patch: IOError: [Errno 0] Error
With this patch:    RuntimeError: Error reading trace header (index 0)
=> Clarify what fails in segyio.tools.dt

breaking-changes.md, python/segyio/_field.py, python/segyio/_trace.py, python/segyio/open.py, python/segyio/segy.py, python/segyio/segyio.cpp, python/segyio/tools.py, python/test/segyio_c.py
=> WIP Extension-in-C++

applications/apputils.c, applications/segyio-catr.c, lib/include/segyio/segy.h, man/segyio-catr.1
This is just a set of minor fixes and patches of small errors, and not a cohesive change.
=> Cleanup, fixes and documentation

python/docs/segyio.rst, python/segyio/segy.py, python/segyio/trace.py, python/test/segy.py
=> Trace iterable update disk

CMakeLists.txt, applications/CMakeLists.txt
Build applications by default, but make it opt-out.
=> Make building applications optional

python/segyio/tools.py, python/test/tools.py
=> Helper function to create a SEGY file from a 2D/3D numpy array

python/segyio/binfield.py, python/segyio/segy.py, python/segyio/segysampleformat.py, python/segyio/tools.py, python/segyio/tracefield.py, python/segyio/tracesortingformat.py, python/test/segy.py, python/test/segyio_c.py, python/test/tools.py
Pycharm doesn't complain about the code, with some additional setup able to run tests from IDE.
Worked on 2.7, IDE and ctest, waiting for other versions confirmation
=> Tidying up imports

lib/src/segy.c, lib/test/segy.cpp, python/segyio/create.py
=> Delay recording time documentation update

.pylintrc, python/segyio/depth.py, python/segyio/tools.py
=> codacy warning ignore

python/segyio/trace.py
Added a one liner to perform a resample of the trace (e.g from 4ms sample rate to 2ms sample rate)
=> Added example for a trace resample in doc string

python/segyio/trace.py
Several nested try-except blocks etc. led to slightly convoluted code.
=> Clean up subtrace code

README.md
Hi @jokva, I've just added a Documentation heading (h3) to the README file.
=> Add Documentation heading to README

lib/test/segy.cpp
=> Test case for make source water depth 4 not 2

README.md, python/segyio/segyio.cpp
Hi, I would like to suggest two small changes, both related to the "unable to find sorting" message. One in the README.md, one in the message itself. I know I spent a little longer I would like to admit trying to understand why that was happening a while ago and I know a colleague bumped in the same issue recently. I hope this modification is helpful!
=> Raplima docupdate 1

python/segyio/gather.py, python/test/segy.py
Fixes https://github.com/equinor/segyio/issues/499
=> Fix gather to sanitize the offsets slice

external/catch2/catch/catch.hpp
Hello folks from Equinor,
I've been packaging segyio for the [Nix package manager](nixos.org) but I stumbled upon the catch2 error described [here](https://github.com/catchorg/Catch2/issues/2178). It has been solved in more recent versions of catch2, so I'm making this PR to bump the version in order to fix it.
Cheers!
=> catch2: v2.2.3 -> v2.13.9

changelog.md, python/docs/conf.py, python/setup.cfg
=> Bump version tag to 1.9.13

.github/workflows/analyzers.yaml, .github/workflows/build.yaml, .github/workflows/wheels.yaml, applications/segyio-catb.c, lib/experimental/segyio/segyio.hpp, lib/src/segy.c, lib/test/segy.cpp, lib/test/segyio-cpp.cpp
Hopefully these workflows will help us with coming updates, now that we know that we will be drowning in type changes, and will help us focus on making conscious type choices.
Main goal was to have a clean warnings state. Some fixes are forced conversion because of mismatched current types. Some are not fixed, just ignored, as I have no clue how to do that.
=> Add more checks to build workflows

cppcheck/segyio.cfg, lib/include/segyio/segy.h, lib/src/segy.c
First part of changes allowing users to supply their own IO.
This one makes changes only to internal library, opening up for introducing new functionality in python later.
Note: I can't figure out if we shouldn't just delete cppcheck segyio.cfg - I am not sure if it helps cppcheck to know about possible leaks (then it should stay and be maintained) or if it is just more or less useless for us.
This is a question for future. For now I just updated there function signatures.
=> BYOIO: changes in C core
